version: "2"
services:
  web:
    container_name: forum.apache
    image: gravatalonga/docker-apache2laravel
    ports:
      - "80:80"
    volumes:
      - forum-app:/opt/application:nocopy
    links:
      - php

  php:
    container_name: forum.php
    image: gravatalonga/docker-php7.0
    ports:
      - "9001:9001"
      - "22:22"
    volumes:
      - forum-app:/opt/application:nocopy
    links:
      - db
      - redis
      - mailhog

  db:
    container_name: forum.maria
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=control

  redis:
    container_name: forum.redis
    image: redis
    ports:
      - "6379:6379"

  mailhog:
    container_name: forum.mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  blackfire:
    container_name: forum.blackfire
    image: blackfire/blackfire
    environment:
        - BLACKFIRE_SERVER_ID
        - BLACKFIRE_SERVER_TOKEN

volumes:
  forum-app:
    external: true